services:
  songrequesttracker-api:
    build: ./api
    container_name: songrequesttracker-api
    ports:
      - "8066:8080"
    volumes:
      - ./api/data:/api/data
    networks:
      - backend
  songrequesttracker-bot:
    build:
      ./bot
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
      - CHANNEL=${CHANNEL}
    container_name: songrequesttracker-bot
    depends_on:
      - "songrequesttracker-api"
    networks:
      - backend

networks:
  backend:
    driver: bridge