services:
  songrequesttracker-api:
    build: ./api
    container_name: songrequesttracker-api
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./api/data:/api/data
    networks:
      - app
  songrequesttracker-bot:
    build:
      ./bot
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
      - CHANNELS=${CHANNELS}
    container_name: songrequesttracker-bot
    depends_on:
      - "songrequesttracker-api"
    networks:
      - app
  songrequesttracker-frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    container_name: songrequesttracker-frontend
    networks:
      - app
networks:
  app:
    driver: bridge