version: "3"
services:
  songrequesttracker-api:
    build: ./api
    container_name: songrequesttracker-api
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - ./api/data:/api/data
    networks:
      - songrequesttracker
  songrequesttracker-bot:
    build:
      ./bot
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
      - CHANNELS=${CHANNELS}
    container_name: songrequesttracker-bot
    depends_on:
      - "songrequesttracker-api"
    networks:
      - songrequesttracker
  songrequesttracker-frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKENDAPI=${BACKENDAPI}
    ports:
      - "${FRONTEND_PORT}:80"
    container_name: songrequesttracker-frontend
    depends_on:
      - "songrequesttracker-api"
    networks:
      - songrequesttracker

networks:
  songrequesttracker:
    driver: bridge