services:
  songrequesttracker-api:
    build: ./api
    container_name: songrequesttracker-api
    ports:
      - "8066:8080"
  songrequesttracker-bot:
    build:
      ./bot
    environment:
      - USERNAME="${USERNAME}"
      - TOKEN="${TOKEN}"
    container_name: songrequesttracker-bot