services:
  songrequesttracker-api:
    build: ./api
    container_name: songrequesttracker-api
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./api/data:/api/data
    networks:
      - backend
  songrequesttracker-bot:
    build:
      ./bot
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
      - CHANNELS=${CHANNELS}
    container_name: songrequesttracker-bot
    depends_on:
      - "songrequesttracker-api"
    networks:
      - backend

networks:
  backend:
    driver: bridge